name: linting
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing npm
        run: make install
      - name: Linting
        run: make lint
